"""ubah nama tabel

Revision ID: bf61197711f1
Revises: 
Create Date: 2026-08-12 15:32:28.351047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf61197711f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama_barang', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('harga', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jumlah_barang', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('barang_pkey'))
    )
    # ### end Alembic commands ###
